Update documentation for questions
dodona-edu/dodona-edu.github.io pull request #243
Opened 2023-05-17 12:23 UTC by jorg-vr

I updated the documentation about asking questions on the exercise page.

I also updated the english page to match the dutch page

2023-05-17 12:26 UTC, pdawyndt commented
Would it be an idea to use the platform announcement feature to address the new features from the latest release for making annotations (reply to annotation, multiline selection, representation of machine annotations, ...), with a reference to the updated documentation page on asking questions?

2023-05-17 12:42 UTC, niknetniko approved these changes

2023-05-21 19:15 UTC, bmesuere commented
> Would it be an idea to use the platform announcement feature to address the new features from the latest release for making annotations (reply to annotation, multiline selection, representation of machine annotations, ...), with a reference to the updated documentation page on asking questions?

No, this is only for urgent messages since they are shown on all pages. There is an open issue to show such info on the home page as part of the next phase of the home page rework.

2023-05-21 19:20 UTC, bmesuere requested changes

2023-05-21 19:20 UTC, bmesuere commented on en/guides/students/exercises/README.md
> -title: "[nl] Oefeningen oplossen"
Why was the nl tag removed? We put this in title for Dutch pages on the English part of the website.

2023-05-21 19:20 UTC, bmesuere commented on en/guides/students/exercises/README.md
> +Nadat je je oplossing hebt ingediend, kan je op drie manieren een vraag stellen. Bovenaan de ingediende code kan je een algemene vraag stellen door op `Stel een vraag over je code` te klikken. Daarna
```suggestion
Nadat je je oplossing hebt ingediend, kan je op drie manieren een vraag stellen. Bovenaan de ingediende code kan je een algemene vraag stellen door op `Stel een vraag over je code` te klikken. Daarnaast kan je links van het regelnummer op de roze cirkel klikken een vraag stellen bij een specifieke regel code. Je kan ook een stuk code selecteren en dan hierover vragen stellen via diezelfde knop.
```

2023-05-21 19:20 UTC, bmesuere commented on nl/guides/students/exercises/README.md
> +title: "[nl]Oefeningen oplossen"
Since this page is in Dutch and on the Dutch part of the website, the nl tag shouldn't be here.

2023-05-21 19:20 UTC, bmesuere commented on nl/guides/students/exercises/README.md
> +Nadat je je oplossing hebt ingediend, kan je op drie manieren een vraag stellen. Bovenaan de ingediende code kan je een algemene vraag stellen door op `Stel een vraag over je code` te klikken. Daarna
```suggestion
Nadat je je oplossing hebt ingediend, kan je op drie manieren een vraag stellen. Bovenaan de ingediende code kan je een algemene vraag stellen door op `Stel een vraag over je code` te klikken. Daarnaast kan je links van het regelnummer op de roze cirkel klikken een vraag stellen bij een specifieke regel code. Je kan ook een stuk code selecteren en dan hierover vragen stellen via diezelfde knop.
```

2023-05-24 07:51 UTC, bmesuere approved these changes

2023-05-30 07:14 UTC, merged