Introduce teacher documentation for annotations
dodona-edu/dodona-edu.github.io pull request #328
Opened 2023-09-21 13:37 UTC by jorg-vr

This adds a guide about managing questions and comments for teachers.

This guide was made in the context of the release of saved annotations: https://github.com/dodona-edu/dodona/pull/4992

2023-10-06 08:17 UTC, bmesuere commented
@jorg-vr I propose rewriting it to these questions

# Questions and comments

## How can I ask a question about my code? <Badge type="tip" text="student" />

(also add an info box that questions might be disabled)

## How do I know if my question has been answered? <Badge type="tip" text="student" />

## How can I enable/disable student questions? <Badge type="tip" text="teacher" />

## How do I know if there are any open questions? <Badge type="tip" text="teacher" />

## How can I reply to a question from a student? <Badge type="tip" text="teacher" />

## How can I comment on a students' submission? <Badge type="tip" text="teacher" />

## How can I store and reuse comments? <Badge type="tip" text="teacher" />

2023-10-06 08:22 UTC, bmesuere commented
This would also close #169. There is some content in the issue there that could be used here.

2023-10-27 10:12 UTC, pdawyndt commented on en/faq/annotations/index.md
> +If you want to see al open question accross all your courses, you can go to the `questions` page in the navigation sidebar of Dodona.
across

2023-10-27 10:12 UTC, pdawyndt commented on en/faq/annotations/index.md
> +> Note: comments support markdown formatting, so you can use bold, italics, lists, ... You can checkout all markdown features in [this reference](/en/references/exercise-description/#markdown).
Make capital/lowercase spelling of Markdown consistent throughout the text. I suggest "Markdown"

2023-10-27 10:12 UTC, pdawyndt commented on nl/faq/annotations/index.md
> +> Ter zijde: opmerkingen ondersteunen markdown, dus je kan gebruik maken van vet, cursief, lijsten, ... Je kan alle markdown features bekijken in [deze referentie](/nl/references/exercise-description
Markdown

2023-10-27 11:23 UTC, niknetniko requested changes

2023-10-27 11:23 UTC, niknetniko commented on nl/faq/annotations/index.md
> +> Opmerking: deze functionaliteit is enkel beschikbaar als je lesgever dit heeft ingeschakeld.
```suggestion
::: tip Opmerking
Deze functionaliteit is enkel beschikbaar als je lesgever dit heeft ingeschakeld.
:::
```

2023-10-27 11:23 UTC, niknetniko commented on nl/faq/annotations/index.md
> +Je kan ook direct een vraag markeren als beantwoord. Dit is vaak handig als je weet dat de student de vraag al opgelost heeft op een andere manier. Bijvoorbeeld de student heeft een andere oplossing
```suggestion
Je kan ook direct een vraag markeren als beantwoord. Dit is vaak handig als je weet dat de student de vraag al opgelost heeft op een andere manier. Bijvoorbeeld als de student een andere oplossing ingediend heeft waar het probleem opgelost is, of als je de vraag beantwoord hebt buiten Dodona.
```

2023-10-27 11:23 UTC, niknetniko commented on nl/faq/annotations/index.md
> +Je kan een algemene opmerking toevoegen door op de `Globale opmerking toevoegen` knop te klikken. Je kan ook een stuk code selecteren en op de `Voeg opmerking toe` knop klikken om een opmerking toe t
```suggestion
Je kan een algemene opmerking toevoegen door op de knop `Globale opmerking toevoegen` te klikken. Je kan ook een stuk code selecteren en op de knop `Voeg opmerking toe` klikken om een opmerking toe te voegen over dat specifieke stuk code.
```

2023-10-27 11:23 UTC, niknetniko commented on nl/faq/annotations/index.md
> +> Ter zijde: opmerkingen ondersteunen markdown, dus je kan gebruik maken van vet, cursief, lijsten, ... Je kan alle markdown features bekijken in [deze referentie](/nl/references/exercise-description
```suggestion
> Terzijde: opmerkingen ondersteunen Markdown, dus je kan gebruik maken van vet, cursief, lijsten, ... Je kan alle Markdown features bekijken in [deze referentie](/nl/references/exercise-description/#markdown).
```

2023-10-27 11:23 UTC, niknetniko commented on nl/faq/annotations/index.md
> +Als je een opmerking wil hergebruiken in een andere oefening, zal je deze opnieuw moeten opslaan. We onderzoeken momenteel of hoe we dit kunnen verbeteren.
```suggestion
Als je een opmerking wil hergebruiken in een andere oefening, zal je deze opnieuw moeten opslaan. We onderzoeken momenteel hoe we dit kunnen verbeteren.
```

2023-10-30 09:36 UTC, jorg-vr commented on en/faq/annotations/index.md
> +![image](./student.ask_questions.png)
I have made different images for each language now

2023-10-30 09:54 UTC, niknetniko approved these changes

2023-10-30 16:54 UTC, bmesuere approved these changes

2023-10-31 13:28 UTC, merged