Logo added & readthedocs removed
dodona-edu/dodona-edu.github.io pull request #92
Opened 2020-09-07 19:14 UTC by BTWS2

2020-09-10 08:43 UTC, bmesuere requested changes
- I'm not sure I like the navbar icon.
- The old docs link can of course be removed, but the homepage becomes a bit light on text. Maybe "manuals" and "reference pages" in the first paragraph can be linked to their respective pages. A second paragraph linking to the getting started for teachers would also be welcome.

2020-09-10 09:36 UTC, BTWS2 commented
Adding a new paragraph moves the "manuals" and "reference" buttons down, so I added the links. If there isn't a lot of text the buttons for it are just beneath it:

![image](https://user-images.githubusercontent.com/56451049/92707701-cc163a80-f355-11ea-8b58-36f48ecfa269.png)

After changes:
![image](https://user-images.githubusercontent.com/56451049/92712091-7e9bcc80-f359-11ea-9a77-1ee0853f97aa.png)

Do I have to remove the logo?

2020-10-03 19:07 UTC, BTWS2 commented
Commit *students asking questions* is an attempt at resolving #98.

2021-06-28 08:04 UTC, BTWS2 commented
@bmesuere do you have time in the coming weeks to review this pull request?

2021-08-30 12:57 UTC, bmesuere approved these changes

2021-08-30 12:57 UTC, bmesuere commented on en/README.md
> +Are you a teacher and do you want to create your own Dodona course (with existing or own programming exercises)? Have a look at [this getting started guide](guides/teachers/getting-started).
```suggestion
If you are a teacher and want to create your own Dodona course (with existing or own programming exercises), have a look at [this getting started guide](guides/teachers/getting-started).
```

2021-08-30 12:57 UTC, bmesuere commented on nl/guides/students/exercises/README.md
> +Nadat je je oplossing ingediend hebt, kan je op twee manieren een vraag stellen. Bovenaan de ingediende code kan je een algemene vraag stellen door op `STEL EEN VRAAG OVER JE CODE` te klikken. Daarna
```suggestion
Nadat je je oplossing hebt ingediend, kan je op twee manieren een vraag stellen. Bovenaan de ingediende code kan je een algemene vraag stellen door op `Stel een vraag over je code` te klikken. Daarnaast kan je links van het regelnummer op de oranje cirkel klikken een vraag stellen bij een specifieke regel code.
```

2021-08-30 12:57 UTC, bmesuere commented on nl/guides/students/exercises/README.md
> +Typ in het tekstvak de vraag die je aan je leerkracht wil stellen. Je kan Markdown gebruiken om je tekst extra opmaak te geven. Klik als laatste op `VRAAG STELLEN`.
```suggestion
Typ in het tekstvak de vraag die je aan de lesgever wil stellen. Je kan Markdown gebruiken om je tekst extra opmaak te geven. Klik als laatste op `Vraag stellen`.
```

2021-08-30 12:57 UTC, bmesuere commented on nl/guides/students/exercises/README.md
> +Je kan een aantal woorden in een vraag beklemtonen door:
```suggestion
Je kan met Markdown extra opmaak toevoegen door:
```

2021-08-30 12:57 UTC, bmesuere commented on nl/guides/students/exercises/README.md
> +- twee asterisken (\**) of twee liggende streepjes (\__) rond woorden te zetten om het in het vet weer te geven. \*\*vette tekst\*\* wordt bijvoorbeeld weergegeven als **vette tekst**.
```suggestion
- asterisken (\*)  rond woorden te zetten om het schuin weer te geven. \*schuine tekst\* wordt bijvoorbeeld weergegeven als *schuine tekst*.
- twee asterisken (\**) rond woorden te zetten om het in het vet weer te geven. \*\*vette tekst\*\* wordt bijvoorbeeld weergegeven als **vette tekst**.
- backticks (\`) rond een stukje code te zetten. \`Variabelen\` wordt bijvoorbeeld weergegeven als `Variabelen`.
```

2021-08-30 13:00 UTC, merged

2021-08-30 13:00 UTC, bmesuere commented
Sorry for the long delay!